In [1]:
import matplotlib.pyplot as plt 
import numpy as np 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import classification_report, confusion_matrix 

# Generate data
x = np.arange(10).reshape(-1, 1) 
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1]) 

# Train logistic regression model
model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(x, y)

# Model parameters
print("Classes:", model.classes_)
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

# Predictions
print("\nPrediction Probabilities:\n", model.predict_proba(x))
print("Predictions:", model.predict(x))
print("Model Accuracy Score:", model.score(x, y))

# Confusion matrix & classification report
print("\nConfusion Matrix:\n", confusion_matrix(y, model.predict(x)))
print("\nClassification Report:\n", classification_report(y, model.predict(x)))

# Improve Model with Higher Regularization (C=10.0)
print("\n--- Improving Model with C=10.0 ---")
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)

# Print updated model parameters
print("New Intercept:", model.intercept_)
print("New Coefficients:", model.coef_)

# New predictions
print("\nNew Prediction Probabilities:\n", model.predict_proba(x))
print("New Predictions:", model.predict(x))
print("New Model Accuracy Score:", model.score(x, y))

# New confusion matrix & classification report
print("\nNew Confusion Matrix:\n", confusion_matrix(y, model.predict(x)))
print("\nNew Classification Report:\n", classification_report(y, model.predict(x)))


Classes: [0 1]
Intercept: [-1.04608067]
Coefficients: [[0.51491375]]

Prediction Probabilities:
 [[0.74002157 0.25997843]
 [0.62975524 0.37024476]
 [0.5040632  0.4959368 ]
 [0.37785549 0.62214451]
 [0.26628093 0.73371907]
 [0.17821501 0.82178499]
 [0.11472079 0.88527921]
 [0.07186982 0.92813018]
 [0.04422513 0.95577487]
 [0.02690569 0.97309431]]
Predictions: [0 0 0 1 1 1 1 1 1 1]
Model Accuracy Score: 0.9

Confusion Matrix:
 [[3 1]
 [0 6]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10


--- Improving Model with C=10.0 ---
New Intercept: [-3.51335372]
New Coefficients: [[1.12066084]]

New Prediction Probabilities:
 [[0.97106534 0.02893466]
 [0.9162684  0.0837316 ]
 [0.7810904  0.2189096 

In [5]:
import numpy as np  
import pandas as pd  
from sklearn.model_selection import train_test_split  
from sklearn.linear_model import LogisticRegression  
from sklearn.metrics import accuracy_score  

# Create dataset
data = {  
    'Age': [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],  
    'Smoker': [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],  
    'Outcome': [0, 0, 0, 1, 1, 1, 1, 1, 1, 1]  
}
df = pd.DataFrame(data)  

# Split features (X) and target variable (y)
X = df[['Age', 'Smoker']]  
y = df['Outcome']  

# Split the data into training and testing sets  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  

# Train a logistic regression model  
model = LogisticRegression()  
model.fit(X_train, y_train)  

# Make predictions on the test set  
y_pred = model.predict(X_test)  

# Calculate model accuracy  
accuracy = accuracy_score(y_test, y_pred)  
print(f'Accuracy: {accuracy:.2f}')  

# Calculate and display odds ratio  
odds_ratio = np.exp(model.coef_)  
print("\nOdds Ratio for Features:")
for feature, odds in zip(X.columns, odds_ratio[0]):
    print(f"{feature}: {odds:.2f}")


Accuracy: 1.00

Odds Ratio for Features:
Age: 2.05
Smoker: 1.14
