In [19]:
import pandas as pd 
dataset=pd.read_csv(r"C:\Users\yashw\Downloads\annual-enterprise-survey-2023-financial-year-provisional-size-bands.csv")
dataset

year industry_code_ANZSIC               industry_name_ANZSIC  \
0      2011                    A  Agriculture, Forestry and Fishing   
1      2011                    A  Agriculture, Forestry and Fishing   
2      2011                    A  Agriculture, Forestry and Fishing   
3      2011                    A  Agriculture, Forestry and Fishing   
4      2011                    A  Agriculture, Forestry and Fishing   
...     ...                  ...                                ...   
20119  2023                  all                     All Industries   
20120  2023                  all                     All Industries   
20121  2023                  all                     All Industries   
20122  2023                  all                     All Industries   
20123  2023                  all                     All Industries   

        rme_size_grp                                         variable  \
0                a_0                                    Activity unit   
1                a_0                           Rolling mean employees   
2                a_0                          Salaries and wages paid   
3                a_0  Sales, government funding, grants and subsidies   
4                a_0                                     Total income   
...              ...                                              ...   
20119  j_Grand_Total                                     Total income   
20120  j_Grand_Total                                Total expenditure   
20121  j_Grand_Total                      Operating profit before tax   
20122  j_Grand_Total                                     Total assets   
20123  j_Grand_Total                            Fixed tangible assets   

         value               unit  
0        46134              COUNT  
1            0              COUNT  
2          279  DOLLARS(millions)  
3         8187  DOLLARS(millions)  
4         8866  DOLLARS(millions)  
...        ...                ...  
20119   930995  DOLLARS(millions)  
20120   832964  DOLLARS(millions)  
20121   103616  DOLLARS(millions)  
20122  2831894  DOLLARS(millions)  
20123   681890  DOLLARS(millions)  

[20124 rows x 7 columns]

In [21]:
dataset.head()

year industry_code_ANZSIC               industry_name_ANZSIC rme_size_grp  \
0  2011                    A  Agriculture, Forestry and Fishing          a_0   
1  2011                    A  Agriculture, Forestry and Fishing          a_0   
2  2011                    A  Agriculture, Forestry and Fishing          a_0   
3  2011                    A  Agriculture, Forestry and Fishing          a_0   
4  2011                    A  Agriculture, Forestry and Fishing          a_0   

                                          variable  value               unit  
0                                    Activity unit  46134              COUNT  
1                           Rolling mean employees      0              COUNT  
2                          Salaries and wages paid    279  DOLLARS(millions)  
3  Sales, government funding, grants and subsidies   8187  DOLLARS(millions)  
4                                     Total income   8866  DOLLARS(millions)

In [23]:
dataset.tail()

year industry_code_ANZSIC industry_name_ANZSIC   rme_size_grp  \
20119  2023                  all       All Industries  j_Grand_Total   
20120  2023                  all       All Industries  j_Grand_Total   
20121  2023                  all       All Industries  j_Grand_Total   
20122  2023                  all       All Industries  j_Grand_Total   
20123  2023                  all       All Industries  j_Grand_Total   

                          variable    value               unit  
20119                 Total income   930995  DOLLARS(millions)  
20120            Total expenditure   832964  DOLLARS(millions)  
20121  Operating profit before tax   103616  DOLLARS(millions)  
20122                 Total assets  2831894  DOLLARS(millions)  
20123        Fixed tangible assets   681890  DOLLARS(millions)

In [47]:
dataset.head(10)

year industry_code_ANZSIC               industry_name_ANZSIC rme_size_grp  \
0  2011                    A  Agriculture, Forestry and Fishing          a_0   
1  2011                    A  Agriculture, Forestry and Fishing          a_0   
2  2011                    A  Agriculture, Forestry and Fishing          a_0   
3  2011                    A  Agriculture, Forestry and Fishing          a_0   
4  2011                    A  Agriculture, Forestry and Fishing          a_0   
5  2011                    A  Agriculture, Forestry and Fishing          a_0   
6  2011                    A  Agriculture, Forestry and Fishing          a_0   
7  2011                    A  Agriculture, Forestry and Fishing          a_0   
8  2011                    A  Agriculture, Forestry and Fishing          a_0   
9  2011                    A  Agriculture, Forestry and Fishing        b_1-5   

                                          variable  value               unit  
0                                    Activity unit  46134              COUNT  
1                           Rolling mean employees      0              COUNT  
2                          Salaries and wages paid    279  DOLLARS(millions)  
3  Sales, government funding, grants and subsidies   8187  DOLLARS(millions)  
4                                     Total income   8866  DOLLARS(millions)  
5                                Total expenditure   7618  DOLLARS(millions)  
6                      Operating profit before tax    770  DOLLARS(millions)  
7                                     Total assets  55700  DOLLARS(millions)  
8                            Fixed tangible assets  32155  DOLLARS(millions)  
9                                    Activity unit  21777              COUNT

In [49]:
dataset.tail(10)

year industry_code_ANZSIC industry_name_ANZSIC      rme_size_grp  \
20114  2023                    S       Other Services  i_Industry_Total   
20115  2023                  all       All Industries     j_Grand_Total   
20116  2023                  all       All Industries     j_Grand_Total   
20117  2023                  all       All Industries     j_Grand_Total   
20118  2023                  all       All Industries     j_Grand_Total   
20119  2023                  all       All Industries     j_Grand_Total   
20120  2023                  all       All Industries     j_Grand_Total   
20121  2023                  all       All Industries     j_Grand_Total   
20122  2023                  all       All Industries     j_Grand_Total   
20123  2023                  all       All Industries     j_Grand_Total   

                                              variable    value  \
20114                            Fixed tangible assets     5503   
20115                                    Activity unit   540552   
20116                           Rolling mean employees  2004063   
20117                          Salaries and wages paid   147663   
20118  Sales, government funding, grants and subsidies   821630   
20119                                     Total income   930995   
20120                                Total expenditure   832964   
20121                      Operating profit before tax   103616   
20122                                     Total assets  2831894   
20123                            Fixed tangible assets   681890   

                    unit  
20114  DOLLARS(millions)  
20115              COUNT  
20116              COUNT  
20117  DOLLARS(millions)  
20118  DOLLARS(millions)  
20119  DOLLARS(millions)  
20120  DOLLARS(millions)  
20121  DOLLARS(millions)  
20122  DOLLARS(millions)  
20123  DOLLARS(millions)

In [51]:
z=np.ones(10)
type(z[0])
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
z=np.empty(3)
z

array([0., 0., 0.])

In [57]:
z=np.linspace(1,9,5)
z

array([1., 3., 5., 7., 9.])

In [59]:
z=np.array([10,20])
z

array([10, 20])